### ISSUE TITLE
About the Android version of this open source project.

### ISSUE THREAD

**Issue by Xi-You** [DavidMcLaughlin208/FallingSandJava#1]
Hello, I found your open source project some time ago, and I tried to make it run on Android.  

[Android project jump link](https://github.com/Xi-You/FallingSandJava-android/blob/Android/FallingSandJava-android.7z)

The compilation software I use is AIDE.

Because the version you use box2d uses more Java8 syntax and the version I use is Java7, I only tried to run the previous version, and the performance is a bit bad when the game is running.

Would you try to make an Android version?

**Comment by DavidMcLaughlin208** [comment]
I am currently making this project for computers not phones. In its current state I imagine performance would be pretty poor on Android.

You can try reducing the resolution by a lot since right now it is extremely large. This may help with performance. 

I have long term plans for this project to become a PC game. But also shorter term plans to release this incrementally as a classic falling sand simulation for PC and (I hadn't considered it before) possibly also Android.

I would have to look into that but I do not know how long it would take. And I am more focused on adding some more features before releasing as a falling sand simulation.

----

What is your intention of getting this to run on Android?

**Comment by Xi-You** [comment]
Thanks Reply.The way I make it run on Android is to modify your source code so that it can be compiled into an apk.  But there are a lot of Java 8 syntax needs to be modified, I am not very good at this skill.
